# Generated by Django 5.1.15 on 2026-06-10 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='કાર્યક્રમ નામ / Event Title')),
                ('description', models.TextField(verbose_name='વિગત / Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='ફોટો / Photo')),
                ('event_date', models.DateField(verbose_name='તારીખ / Date')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='સમય / Time')),
                ('location', models.CharField(max_length=300, verbose_name='સ્થળ / Location')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Event / કાર્યક્રમ',
                'verbose_name_plural': 'Events / કાર્યક્રમો',
                'ordering': ['-event_date'],
            },
        ),
    ]
