# Generated by Django 5.1.15 on 2026-06-10 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='શીર્ષક / Title')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ફોટો / Photo')),
                ('category', models.CharField(choices=[('samuh_lagan', 'સમૂહ લગ્ન / Samuh Lagan'), ('sneh_milan', 'સ્નેહ મિલન / Sneh Milan'), ('yuva', 'યુવા મિલન / Yuva Milan'), ('community', 'સામુદાયિક / Community'), ('other', 'અન્ય / Other')], default='community', max_length=50, verbose_name='શ્રેણી / Category')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Image / ગેલેરી ફોટો',
                'verbose_name_plural': 'Gallery Images / ગેલેરી ફોટા',
                'ordering': ['-created_at'],
            },
        ),
    ]
