# Generated by Django 5.1.15 on 2026-06-10 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samaj_name', models.CharField(default='ગુજરાતી સમાજ', max_length=300)),
                ('samaj_name_en', models.CharField(default='Gujarati Samaj', max_length=300)),
                ('address', models.TextField(verbose_name='સરનામું / Address')),
                ('phone', models.CharField(max_length=20, verbose_name='ફોન / Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='ઈ-મેઈલ / Email')),
                ('about', models.TextField(blank=True, verbose_name='સમાજ વિશે / About Samaj')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='Google Map URL')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=200, verbose_name='કુટુંબ નામ / Family Name')),
                ('village', models.CharField(max_length=200, verbose_name='ગામ / Village')),
                ('gotra', models.CharField(choices=[('kashyap', 'કાશ્યપ / Kashyap'), ('bharadwaj', 'ભારદ્વાજ / Bharadwaj'), ('atri', 'અત્રિ / Atri'), ('vasishtha', 'વસિષ્ઠ / Vasishtha'), ('vishwamitra', 'વિશ્વામિત્ર / Vishwamitra'), ('other', 'અન્ય / Other')], max_length=100, verbose_name='ગોત્ર / Gotra')),
                ('address', models.TextField(verbose_name='સરનામું / Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='મોબાઈલ / Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ઈ-મેઈલ / Email')),
                ('business', models.CharField(choices=[('agriculture', 'કૃષિ / Agriculture'), ('business', 'વ્યવસાય / Business'), ('service', 'નોકરી / Service'), ('professional', 'વ્યવસાયિક / Professional'), ('other', 'અન્ય / Other')], max_length=100, verbose_name='વ્યવસાય / Business')),
                ('family_photo', models.ImageField(blank=True, null=True, upload_to='family_photos/', verbose_name='કુટુંબ ફોટો')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Family / કુટુંબ',
                'verbose_name_plural': 'Families / કુટુંબો',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='નામ / Name')),
                ('relation', models.CharField(choices=[('head', 'મુખ્ય / Head'), ('wife', 'પત્ની / Wife'), ('son', 'પુત્ર / Son'), ('daughter', 'પુત્રી / Daughter'), ('daughter_in_law', 'પુત્રવધૂ / Daughter-in-law'), ('son_in_law', 'જમાઈ / Son-in-law'), ('father', 'પિતા / Father'), ('mother', 'માતા / Mother'), ('brother', 'ભાઈ / Brother'), ('sister', 'બહેન / Sister'), ('grandfather', 'દાદા / Grandfather'), ('grandmother', 'દાદી / Grandmother'), ('other', 'અન્ય / Other')], max_length=50, verbose_name='સંબંધ / Relation')),
                ('gender', models.CharField(choices=[('male', 'પુરુષ / Male'), ('female', 'સ્ત્રી / Female'), ('other', 'અન્ય / Other')], max_length=10, verbose_name='જાતિ / Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='જન્મ તારીખ / Date of Birth')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='શિક્ષણ / Education')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='વ્યવસાય / Occupation')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='મોબાઈલ / Mobile')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='ફોટો / Photo')),
                ('is_active', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family', verbose_name='કુટુંબ / Family')),
            ],
            options={
                'verbose_name': 'Member / સભ્ય',
                'verbose_name_plural': 'Members / સભ્યો',
                'ordering': ['family', 'name'],
            },
        ),
    ]
