# Generated by Django 5.1.15 on 2026-06-10 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='શીર્ષક / Title')),
                ('description', models.TextField(verbose_name='વિગત / Description')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='પ્રકાશન તારીખ / Publish Date')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Announcement / જાહેરાત',
                'verbose_name_plural': 'Announcements / જાહેરાતો',
                'ordering': ['-publish_date'],
            },
        ),
    ]
